# Generated by Django 5.0 on 2023-12-15 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_remove_persona_correo_remove_persona_telefono_correo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='correo',
            old_name='direccion',
            new_name='correo',
        ),
    ]
