# Generated by Django 5.0 on 2023-12-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_rename_direccion_correo_correo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telefono',
            old_name='numero',
            new_name='telefono',
        ),
    ]
